import os
import uuid
import hashlib
from xml.etree.ElementTree import Element, SubElement, ElementTree, indent

def _calc_md5(file_path: str) -> str:
    md5 = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            md5.update(chunk)
    return md5.hexdigest().upper()

def generate_modinfo(output_dir: str, files: list[str]) -> str:
    """
    Generate a Civ5 .modinfo file in output_dir.

    :param output_dir: Translation mod root directory
    :param files: List of relative file paths inside output_dir
    :return: Full path to generated .modinfo file
    """

    mod_name = os.path.basename(output_dir)
    mod_id = str(uuid.uuid4())

    modinfo_path = os.path.join(output_dir, f"{mod_name}.modinfo")

    root = Element("Mod", {
        "id": mod_id,
        "version": "1"
    })

    # ---- Properties ----
    props = SubElement(root, "Properties")
    SubElement(props, "Name").text = mod_name
    SubElement(props, "Teaser").text = mod_name
    SubElement(props, "Description").text = mod_name
    SubElement(props, "Authors").text = "Generated by Civ5Tool"
    SubElement(props, "AffectsSavedGames").text = "1"
    SubElement(props, "SupportsSinglePlayer").text = "1"
    SubElement(props, "SupportsMultiplayer").text = "1"

    # ---- Files ----
    files_node = SubElement(root, "Files")

    for rel_path in files:
        abs_path = os.path.join(output_dir, rel_path)

        if not os.path.isfile(abs_path):
            continue

        md5 = _calc_md5(abs_path)

        file_node = SubElement(files_node, "File", {
            "md5": md5,
            "import": "0"
        })
        file_node.text = rel_path.replace("\\", "/")

    # ---- Actions ----
    actions = SubElement(root, "Actions")
    on_activated = SubElement(actions, "OnModActivated")

    for rel_path in files:
        update = SubElement(on_activated, "UpdateDatabase")
        update.text = rel_path.replace("\\", "/")

    # ---- Write file ----
    tree = ElementTree(root)
    indent(tree, space="  ", level=0)
    tree.write(modinfo_path, encoding="utf-8", xml_declaration=True)

    return modinfo_path